version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  redis-insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

volumes:
  dynamodb-data: {}
