version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - '11211:11211'
